vim.keymap.set("n", "<leader>L", "", { desc = "LSP", noremap = false, silent = true })
vim.keymap.set("n", "<leader>LD", "", { desc = "Document", noremap = false, silent = true })
vim.keymap.set("n", "<leader>LW", "", { desc = "Workspace", noremap = false, silent = true })

vim.keymap.set("n", "<leader>LI", function()
    vim.cmd [[checkhealth lsp]]
end, { desc = "LSP Info", noremap = false, silent = true })
vim.keymap.set("n", "<leader>La", function()
    vim.lsp.buf.code_action()
end, { desc = "Code Action", noremap = false, silent = true })
vim.keymap.set("n", "<leader>Lf", function()
    vim.lsp.buf.format()
end, { desc = "Format", noremap = false, silent = true })
vim.keymap.set("n", "<leader>Ll", function()
    vim.lsp.codelens.run()
end, { desc = "CodeLens Action", noremap = false, silent = true })
vim.keymap.set("n", "<leader>Ln", function()
    vim.lsp.buf.rename()
end, { desc = "Rename", noremap = false, silent = true })
-- vim.keymap.set("n", "<leader>Lk", function()
--     vim.lsp.buf.hover { border = "solid" }
-- end, { desc = "Hover", noremap = false, silent = true })
vim.keymap.set("n", "<leader>LWa", function()
    vim.lsp.buf.add_workspace_folder()
end, { desc = "Add Workspace Folder", noremap = false, silent = true })
vim.keymap.set("n", "<leader>LWr", function()
    vim.lsp.buf.remove_workspace_folder()
end, { desc = "Remove Workspace Folder", noremap = false, silent = true })
vim.keymap.set("n", "<leader>LWl", function()
    vim.lsp.buf.list_workspace_folders()
end, { desc = "List Workspace Folders", noremap = false, silent = true })
vim.keymap.set("n", "<leader>LWd", function()
    vim.diagnostic.setqflist()
end, { desc = "Workspace Diagnostics", noremap = false, silent = true })
vim.keymap.set("n", "<leader>LDd", function()
    vim.diagnostic.setloclist()
end, { desc = "Document Diagnostics", noremap = false, silent = true })
vim.keymap.set("n", "<leader>LC", function()
    vim.lsp.codelens.run()
end, { desc = "Run CodeLens action" })
